# Generated by Django 3.2.20 on 2023-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0003_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="package",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
