# Generated by Django 3.2.20 on 2023-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_product_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.IntegerField(),
        ),
    ]
